name = "thinkara-sync-api" # Fixed typo
main = "src/index.ts"
compatibility_date = "2024-09-23" # Updated compatibility date
compatibility_flags = [ "nodejs_compat" ] # Enable Node.js compatibility

# Use the existing KV namespace - the binding name is what our code uses
# The ID is the actual Cloudflare KV namespace ID
kv_namespaces = [
  { binding = "SAVED_ITEMS_KV", id = "19a1b73a994f4e99b583d29485bf6d26" }
]

# Declare the D1 database binding
# The user needs to create a D1 database in the Cloudflare dashboard
# and replace "YOUR_D1_DATABASE_ID_HERE" with the actual ID.
[[d1_databases]]
binding = "USER_DATA_DB" # Name used to access the DB in the worker code
database_name = "user-data" # A nickname for the DB in the dashboard
database_id = "YOUR_D1_DATABASE_ID_HERE"

# Declare environment variables used by the worker
# Actual values are set in Cloudflare dashboard for deployment
# and in .env file for local development
[vars]
# GCF URLs are now managed via secrets, but we declare them here for clarity/local dev fallback if needed
# GCF_AUTH_KEY = ""    # Removed - Using Workload Identity Federation now

# Variables for Workload Identity Federation
GCLOUD_PROJECT_NUMBER = "98706481155"
GCLOUD_WORKLOAD_IDENTITY_POOL_ID = "cf-worker-pool"
GCLOUD_WORKLOAD_IDENTITY_PROVIDER_ID = "cf-oidc-provider"
GCLOUD_SERVICE_ACCOUNT_EMAIL = "frontend-summarizer-invoker@thinkara-455112.iam.gserviceaccount.com" # Assuming project ID should also be renamed, needs verification

# Declare secrets needed for the worker
# Actual values must be set using 'wrangler secret put <KEY>'
# e.g., wrangler secret put CLERK_SECRET_KEY
[secrets]
# CLERK_SECRET_KEY = "" # Uncomment and set value via wrangler secret put

[observability.logs]
enabled = true

[dev]
ip = "127.0.0.1"
port = 8787
local_protocol = "http"
