name = "bondwise-sync-api" # Fixed typo
main = "src/index.ts"
compatibility_date = "2023-10-30"
compatibility_flags = [ "nodejs_compat" ] # Enable Node.js compatibility

# Use the existing KV namespace - the binding name is what our code uses
# The ID is the actual Cloudflare KV namespace ID
kv_namespaces = [
  { binding = "SAVED_ITEMS_KV", id = "19a1b73a994f4e99b583d29485bf6d26" }
]

# Declare environment variables used by the worker
# Actual values are set in Cloudflare dashboard for deployment
# and in .env file for local development
[vars]
GEMINI_API_KEY = "" # Value ignored, declares variable (kept for potential future use)
GCF_URL = ""        # Value ignored, declares variable (HTTPS Trigger URL for the GCF)
# GCF_AUTH_KEY = "" # Removed - Using Workload Identity Federation now

# Variables for Workload Identity Federation
GCLOUD_PROJECT_NUMBER = "98706481155"
GCLOUD_WORKLOAD_IDENTITY_POOL_ID = "cf-worker-pool"
GCLOUD_WORKLOAD_IDENTITY_PROVIDER_ID = "cf-oidc-provider"
GCLOUD_SERVICE_ACCOUNT_EMAIL = "frontend-summarizer-invoker@bondwise-455112.iam.gserviceaccount.com"

[observability.logs]
enabled = true
