name = "bondwise-sync-api"
main = "src/index.ts"
compatibility_date = "2023-10-30"

# Use the existing KV namespace - the binding name is what our code uses
# The ID is the actual Cloudflare KV namespace ID
kv_namespaces = [
  { binding = "SAVED_ITEMS_KV", id = "19a1b73a994f4e99b583d29485bf6d26" }
]

# Declare environment variables used by the worker
# Actual values are set in Cloudflare dashboard for deployment
# and in .env file for local development
[vars]
GEMINI_API_KEY = "" # Value ignored, declares variable (kept for potential future use)
GCF_URL = ""        # Value ignored, declares variable (HTTPS Trigger URL for the GCF)
GCF_AUTH_KEY = ""   # Value ignored, declares variable (Secret key for GCF authentication)

[observability.logs]
enabled = true
